title: Wtfismyblockchainstrategy

#ga_tag: UA-1974-1

github_corner:
  url: http://github.com/pikesley/wtfismyblockchainstrategy
  colour: '#333'

homepage:
  name: sam
  url: http://sam.pikesley.org

bootswatch: flatly
